tasks:
  - before: |
      npm i -g @angular/cli

ports:
  - port: 4200
    visibility: public

vscode:
  extensions:
    - esbenp.prettier-vscode
    - Angular.ng-template
    - dbaeumer.vscode-eslint
